frappe: keep debug=False for has_permission doctype controller (#1763)
* an update to frappe verson shows

TypeError: FOSSEventCFPSubmission.has_permission() got an unexpected keyword argument 'debug'

Thus private image files were not even visible to logged-in users if set in doctype (via desk)

Noticed since shree was attaching files as "private" for these doctypes